version: "2"

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    env_file:
      - .env
    volumes:
      - /home/kfergani/data/mysql:/var/lib/mysql
    networks:
      - docker_network
    restart: always
  nginx:
    build: ./requirements/nginx
    image: nginx
    env_file:
      - .env
    ports:
      - 443:443
    depends_on: 
      - wordpress
    volumes:
      - /home/kfergani/data/wordpress:/var/www/html/wordpress
    networks:
      - docker_network
    restart: always
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    env_file:
      - .env
    depends_on: 
      - mariadb
    volumes:
      - /home/kfergani/data/wordpress:/var/www/html/wordpress
    networks:
      - docker_network
    restart: always

networks:
  docker_network: